# Generated by Django 5.0.4 on 2024-04-08 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_naseeba', '0002_remove_image_url_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtRequirementsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('background_image', models.ImageField(upload_to='images/background_images/')),
                ('combined_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/member_photos/')),
                ('dress', models.ImageField(upload_to='images/member_dresses/')),
                ('description', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='admin_naseeba.artrequirementsform')),
            ],
        ),
    ]
