# Generated by Django 5.0.4 on 2024-04-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_naseeba', '0003_artrequirementsform_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='form',
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='dress',
            field=models.ImageField(blank=True, upload_to='images/dresses/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/members/'),
        ),
        migrations.CreateModel(
            name='ArtRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('background_image', models.ImageField(upload_to='images/backgrounds/')),
                ('combined_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, to='admin_naseeba.member')),
            ],
        ),
        migrations.DeleteModel(
            name='ArtRequirementsForm',
        ),
    ]
