# Generated by Django 5.0.4 on 2024-04-09 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_naseeba', '0004_remove_member_form_alter_member_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artrequirement',
            name='members',
            field=models.ManyToManyField(to='admin_naseeba.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dress',
            field=models.ImageField(upload_to='images/dresses/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(upload_to='images/members/'),
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Due', 'Due'), ('Paid', 'Paid'), ('Pending', 'Pending')], max_length=20)),
                ('expected_date', models.DateField()),
                ('due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], max_length=20)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('remark', models.TextField(blank=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_naseeba.artrequirement')),
            ],
        ),
    ]
