# Generated by Django 5.0.4 on 2024-04-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_naseeba', '0005_alter_artrequirement_members_alter_member_dress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='due',
            new_name='total',
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='expected_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='payment_status',
            field=models.CharField(choices=[('Due', 'Due'), ('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='product_status',
            field=models.CharField(choices=[('Not Yet Confirmed', 'Not Yet Confirmed'), ('Confirmed', 'Confirmed'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Not Yet Confirmed', max_length=20),
        ),
    ]
