# Generated by Django 5.0.4 on 2024-04-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_naseeba', '0006_rename_due_orderstatus_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
