# Generated by Django 5.0.4 on 2024-04-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_naseeba', '0007_alter_orderstatus_expected_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='images/payment_screenshots/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_naseeba.orderstatus')),
            ],
        ),
    ]
