# Generated by Django 5.0.4 on 2024-04-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_naseeba', '0008_paymentscreenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentscreenshot',
            old_name='screenshot',
            new_name='payment_screenshot',
        ),
    ]
