# Generated by Django 5.0.4 on 2024-04-11 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_naseeba', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artrequirement',
            name='members',
        ),
        migrations.AddField(
            model_name='member',
            name='requirement',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='admin_naseeba.artrequirement'),
            preserve_default=False,
        ),
    ]
