# Generated by Django 5.0.4 on 2024-04-16 07:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_naseeba', '0011_remove_artrequirement_members_member_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='images/blog/blog_images/')),
                ('author_photo', models.ImageField(default='images/blog/default.jpg', upload_to='images/blog/author_photos/')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_naseeba.artrequirement')),
            ],
        ),
    ]
